export default {
  id: '6059a1dd046d511c2fcb45d9',
  tier: 6,
  logoUri: '',
  name: 'A & K DESIGNS',
  region: 'AMERICAS',
  category: 0,
  contact: { name: '0', telephone: '0', email: '0', jobTitle: 'jobTitle' },
  entity: 1,
  coordinate: { longitude: -122.077003, latitude: 45.963299 },
  business: {
    businessType: 0,
    entityType: 1,
  },
  location: {
    address: '8564 NE ALDERWOOD ROAD',
    postalCode: '000000',
    state: 'OREGON',
    city: 'PORTLAND',
    region: 'United States of America',
  },
  officialContact: {
    telephone: '888-8888-8888',
    officialEmail: 'info@dummy.com',
    websiteUrl: 'http://www.dummy.com',
  },
  groupId: '6059a1dd046d511c2fcb45d8',
  registration: {
    registrationName: 'A & K DESIGNS',
    registrationNumber: '3175669',
    registrationType: 'dummy type',
  },
  overallStatus: {
    companyStatus: 0,
    sanction: 0,
    ultimateOwners: 'Will Simith',
    beneficialOwners: 'Jane Done',
    revenue: 75278481,
    employeeNum: 10000,
  },
  dAndB: {
    businessRiskLevel: 1,
    rating: '2A1',
    padex: 15,
    financialStrength: 11,
    compositeCreditAppraisal: 1,
    financialRisk: 0,
    viabilityRating: '14AA',
    viabilityScore: 9,
  },
}
