export const top50Airports = [
  'HKG - Hong Kong International Airport',
  'MEM - Memphis International Airport',
  'PVG - Shanghai Pudong International Airport',
  'SDF - Louisville International Airport',
  'ICN - Incheon International Airport',
  'ANC - Ted Stevens Anchorage International Airport',
  'DXB - Dubai International Airport',
  'DOH - Hamad International Airport',
  'TPE - Taiwan Taoyuan International Airport',
  'NRT - Tokyo Narita International Airport',
  'CDG - Aéroport de Paris-Charles de Gaulle',
  'MIA - Miami International Airport',
  'FRA - Frankfurt Airport',
  'LAX - Los Angeles International Airport',
  'SIN - Singapore Changi Airport',
  'PEK - Beijing Capital International Airport',
  'CAN - Guangzhou Bai Yun International Airport',
  "ORD - O' Hare International Airport",
  'LHR - London Heathrow Airport',
  'AMS - Amsterdam Airport Schiphol',
  'BKK - Suvarnabhumi International Airport',
  'HND - Tokyo Haneda Airport',
  'JFK - John F. Kennedy International Airport',
  'SZX - Shenzhen Baoan International Airport',
  'LEJ - Flughafen Leipzig/Halle',
  'CVG - Cincinnati/Northern Kentucky International Airport',
  'DEL - Indira Gandhi International Airport',
  'IND - Indianapolis International Airport',
  'DWC - Dubai World Central',
  'BOM - Chhatrapati Shivaji International Airport',
  'LGG - Liège Airport',
  'DFW - Dallas/Ft Worth International Airport',
  'LUX - Luxembourg-Findel International Airport',
  'KIX - Kansai International Airport',
  'CGN - Köln-Bonn Airport',
  'EWR - Newark Liberty International Airport',
  'ISL - Atatürk International Airport',
  'BOG - Aeropuerto Internacional El Dorado',
  'MNL - Ninoy Aquino International Airport',
  'KUL - KL International Airport',
  'ONT - LA/Ontario International Airport',
  'HAN - Noi Bai International Airport',
  'HGH - Hangzhou Xiaoshan International Airport',
  'CTU - Chengdu Shuangliu International Airport',
  'ATL - Hartsfield-Jackson Atlanta International Airport',
  'CGK - Soekarno-Hatta International Airport',
  'MAD - Madrid-Barajas Airport',
  'AUH - Abu Dhabi International Airport',
  'OAK - Oakland International Airport',
  'MEX - Mexico City International Airport',
]
export const top50Ports = new Set([
  'Shanghai',
  'Tanjong Pagar',
  'Shenzhen',
  'Ningbo',
  'Guangzhou',
  'Pusan',
  'Hong Kong',
  'Qingdao',
  'Tianjin',
  'Jebel Ali',
  'Rotterdam',
  'Pusan',
  'Antwerp',
  'Kaohsiung',
  'Xiamen',
  'Dalian',
  'Port Angeles',
  'Tanjung Pelepas,',
  'Hamburg-Harburg',
  'Huntington Beach',
  'Laem Chabang',
  'Tanjung Priok',
  'New York-New Jersey',
  'Colombo',
  'Yingkou',
  'Ho Chi Min City',
  'Bremerhaven',
  'Manila',
  'Jawaharlal Nehru',
  'Piraeus',
  'Algeciras',
  'Lianyungang',
  'Tokyo',
  'Mundra',
  'Savannah',
  'Jeddah',
  'Santos',
  'Rizhao',
  'Colon',
  'Felixstowe',
  'Seattle',
  'Dongguan',
  'Tanger Med',
  'Barcelona',
  'Vancouver',
  'Salalah',
  'Fuzhou',
  'Marsaxlokk',
  'Nanjing',
  'Cai Mep',
])
